### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by xDShot** [MarioMey/rotation_mode_addon#2]
```
Traceback (most recent call last):
  File "/home/xdshot/Documents/myproject.blend/quats_to_euler.py", line 185, in <module>
  File "/home/xdshot/Documents/myproject.blend/quats_to_euler.py", line 157, in convert_one_act_every_bon
AttributeError: 'NoneType' object has no attribute 'name'
Error: Python script fail, look in the console for now...
```

fails when run change_rotation_mode_old.py script in text editor. The addon version outputs similar error.

**Comment by MarioMey** [comment]
I don't run Blender since... I don't remember. But maybe I remember that error... and let me see if I fixed it here.

Meanwhile, tell me what you tried to do, and how that bones actions are formed (which groups does they have). And upload a simple file which causes the error.
